language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  # supertest >=0.12.0 uses superagent >=0.18.0, which uses util.deprecate from node >=0.8
env:
  # express 3.0 was released late 2012
  # gm 1.2.0 added extent and gravity
  # mime 1.1.0 added extension
  - MODULES="express@~3 gm@1.2.0 mime@1.1.0"
  - MODULES=""
install:
  - npm install $MODULES
  - npm install
after_script:
  # @see https://github.com/cainus/node-coveralls#istanbul
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
